### PR TITLE
Update active_cname.js

### PR DESCRIPTION
**Pull request by OpAayush**
- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

### CODE REVIEW

**Comment by willin** [comment]
404 not found

**Comment by OpAayush** [comment]
That is for my discord bot dashboard i will put some template there

**Comment by willin** [comment]
https://github.com/willin/js.cool/blob/master/README.en.md#principe

**Comment by OpAayush** [comment]
Hmmm see this https://replit.com/@RPGAMERBG/Discordgg#index.html

**Comment by OpAayush** [comment]
What happened bro

**Pull request closed without merging**
