### PR TITLE
add Subdomain For VM OA

### PR DESCRIPTION
**Pull request by zcns**
- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

### CODE REVIEW

**Comment by zcns** [comment]
This is the domain name applied for for by SIG VM Pages.
[VMSS](httpsl//gitee.com/vmss)

**Review by willin — CHANGES_REQUESTED** [review]
Site 404

**Comment by zcns** [comment]
I haven't added the CNAME file yet, it's now added

**Comment by zcns** [comment]
Added project homepage

**Comment by zcns** [comment]
Not now, site404 anymore.

**Comment by willin** [comment]
image
。。。

**Comment by zcns** [comment]
Forgot to upload Documents

**Comment by zcns** [comment]
be sorry

**Review by willin — APPROVED** [review]

**Pull request merged**
