### PR TITLE
add my cname in active_cname.js file

### PR DESCRIPTION
**Pull request by verma-sanjeet**
- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

### CODE REVIEW

**Comment by verma-sanjeet** [comment]
Hello @willin
can you please let me know the reason this PR is closed?
is there anything needs to be changed on this?

**Comment by willin** [comment]
why u register so many accounts...

**Comment by verma-sanjeet** [comment]
> why u register so many accounts...

Hello @willin 

we have one organisation and we have to lot's of accounts and we want to publish all the accounts on domain and please let me know if we are something doing a wrong ?

Thanks

**Comment by willin** [comment]
> why u register so many accounts...

pls contribute to open source projects first.

**Pull request closed without merging**
