### PR TITLE
Update active_cname.js

### PR DESCRIPTION
**Pull request by pythoniaweb**
- [x] 申请该域名有实际的用途
- [x] 我已经阅读并遵守限定条款

---

I wana make discord bot lit named better list this why i need this domain note from hosting

this one isnt important i think i need only cname 100% but file idk
`If you are using a service like Cloudflare (with "orange cloud") that rewrites domain records, you can add a TXT Record for verification purposes.`
replit-verify=a7532499-c7f0-4d84-b45a-7ba31e385693

### CODE REVIEW

**Comment by willin** [comment]
image

**Comment by pythoniaweb** [comment]
Changes cname is same website link https://list.aggsjakhabsj.repl.co

**Comment by pythoniaweb** [comment]
Nvm i changed cname to a7532499-c7f0-4d84-b45a-7ba31e385693.id.repl.co

**Comment by pythoniaweb** [comment]
no need anymore i got better domain for this

**Pull request closed without merging**
