### PR TITLE
prettier + small changes

### PR DESCRIPTION
**Pull request by WilliamDavidHarrison**

### CODE REVIEW

**Comment by willin** [comment]
`//noCF` it's a convention,  same with  js.org.

**Comment by WilliamDavidHarrison** [comment]
> `//noCF` it's a convention, same with js.org.

Fixed ad675c8e21120fdc65e8e3631a82627b02a971ae

**Comment by WilliamDavidHarrison** [comment]
> why change `'` into `"`?

It can avoid certain errors I think. Also, prettier automatically changes them.

**Comment by willin** [comment]
here's my default config:

```yml
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: true
trailingComma: none
printWidth: 160
bracketSameLine: true
```

**Comment by WilliamDavidHarrison** [comment]
> here's my default config:
> 
> ```yaml
> tabWidth: 2
> semi: true
> singleQuote: true
> jsxSingleQuote: true
> trailingComma: none
> printWidth: 160
> bracketSameLine: true
> ```

Ok, tomorrow I will run prettier with those options.

**Pull request closed without merging**
