### PR TITLE
Update active_cname.js

### PR DESCRIPTION
**Pull request by y0geshx**
add yogesh.js.cool

### CODE REVIEW

**Comment by willin** [comment]
Archived repo.

**Comment by y0geshx** [comment]
😢 it's was the only free domain which supports vercel.

**Comment by willin** [comment]
see <https://domain.willin.wang>

**Comment by y0geshx** [comment]
i followed you , i try to create a Domain Records , after clicking save nothing happened .

**Comment by willin** [comment]
perhaps u did not add any one.

pending list is empty

**Comment by y0geshx** [comment]
Sir I added cname , please check the pending list.
thankyou 😇

**Comment by willin** [comment]
1

**Comment by y0geshx** [comment]
Sir It's working thank you 🎉

**Comment by willin** [comment]
u'r welcome

**Pull request closed without merging**
